// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nginx

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "nginx", asset.ModuleFieldsPri, AssetNginx); err != nil {
		panic(err)
	}
}

// AssetNginx returns asset data.
// This is the base64 encoded gzipped contents of module/nginx.
func AssetNginx() string {
	return "eJzElb2u2zAMhXc/xYHn3jyAh25dOxXoUBS5ikzbwlUkl6Tz8/aF/JM4qRPkAgmqKRHtcz6KtPiGDzoWCLULhwxQp54K5N/T/zwDShLLrlUXQ4GvGQD0MQjxjhiiRjvBlpSdFdjoPVmlEhXHLXaGXUzhWHaeZJUB0kTWtY2hcnWBynihDGDyZIQK1CY9Q6ou1FLgVy7i8y/IG9U2/50BlSNfStGTvCGYLZ3p09Jjm2Q4du24s5BCWu/9W++wMahxQaANnfLQxij2xASxbNopn/6V1SgxJ5nTiHab4VhOoSWsO2g93lnmc4zpkVAf1unE1klkPaishyJMFWtNTauZ42UFpnWd4zzPJoqmXxfBKdMPOu4jl1exO/meO2vSXS26Gqtut+zpY6g/Z/ijIdiOmYIidNsNMWI1WsB6l/ZtDIFsUhC4YH1XulDjp3GpRefRW7yWWpUnAmtU4y9wkwOVC8DLSI0Jpafr2jwTaXR4mKjk2LYvJRodHiZi+tORvLRuI8rktMwxdudL+/0hECaTGv+1ILNPbd+km224EZxM9v3tNoKiIVMSL+Puuf8+/xfuaD/iShuDEDbGfkBjvzmc+Q1283p2V/rFG270RhUZZjrp1T8zTtlUlbMPjrnTbNmQmsfG3y2DewOJDmbb+ifOo2+D4GCa/Q0AAP//9CqSEA=="
}
