// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package squid

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "squid", asset.ModuleFieldsPri, AssetSquid); err != nil {
		panic(err)
	}
}

// AssetSquid returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/squid.
func AssetSquid() string {
	return "eJx8kEEOwiAURPecYtJ9L8DCnSfwBFimhpQWBBrt7Q1tVUKqs2M+ee9Di4GLRLzPRgsgmWQp0aznRgCBlipS4sqkBKAZu2B8Mm6SOAkAuOS7GJ2eLQXQG1od5TpqMamRX3xOWjwlbsHNfm8OmAWXKZgu7m0JLwVm6t2nPHLk1G9554c/p+LW+nIFPtXo1x8os20ycHm4oKvZH2/OeQNuUvEKAAD//w/mb+4="
}
